spring:
  ai:
    openai:
      api-key: sk-xxx
      base-url: https://api.chatanywhere.tech
      chat:
        options:
          model: gpt-3.5-turbo
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: username
    password: password

logging:
  level:
    # restClient 日志打印
    org.apache.hc.client5.http.wire: debug
